name: Build TCC Companion

on:
  workflow_dispatch: {}   # allows manual Run
  push:
    branches: [ main ]    # builds on pushes to main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller -F -w main.py -n TCC-Companion.exe
      - uses: actions/upload-artifact@v4
        with:
          name: TCC-Companion-win64
          path: dist/TCC-Companion.exe

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller -F main.py -n TCC-Companion
      - uses: actions/upload-artifact@v4
        with:
          name: TCC-Companion-linux64
          path: dist/TCC-Companion
